# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fgId6gscxMe86L4IB4Ft6ETD-WyhMmE

1.Commercial Property Management
"""

len=int(input("enter length in meters"))
wid=int(input("enter width in meters"))
area=len*wid
if area<400:
  print("small plot")
elif 400<=area<1500:
  print("medium plot")
else:
  print("large plot")

"""2.Integrated Health Management app"""

height=int(input("enter height of user in meter "))
weight=float(input("enter weight of user in kg"))
bmi=weight/pow(height,2)
if bmi<2.5:
  print("You are underweight")
elif 2.5<=bmi<7.5:
  print("You have perfect measures")
else:
  print("You are overweight")

"""3.Eductaional Record System6"""

student_info={}
keys=int(input("enter student grade"))
values=input("enter student subject")
a=student_info.append(keys)
b=student_info.append(values)
print()

"""4.Content Recommendation Engine"""

user_name=input("enter user name")
age=int(input("enter user's age"))
if age<10:
  print(user_name+". You are a child.")
elif 10<=age<18:
  print(user_name+". You are a teen.")
elif 18<=age<50:
  print(user_name+". You are an adult. ")
else:
  print(user_name+". You are a senior. ")

"""5.Promotional Email Dispatcher"""

subscriber_id=(1,2,3,4,5,6,7,8,9,10)
i=0
for i in subscriber_id:
  if (i%2==0):
   print("potential target.")
   i += 1
  else:
   print("not a target.")

"""6.Corporate network security system"""

user_passkey='Rain@890'
while True:
  passkey=input("enter a passkey")
  if (user_passkey==passkey):
    print("Correct passkey")
    break
  else:
    print("Incorrect passkey. Try again.")

"""7.Customer feedback analysis tool"""



"""8.Content moderation system"""

letter=input("enter a letter")
def vowels(letter):
  ans=0
  for i in range(0,len(letter)):
    if (letter[i]=='a'or letter[i]=='e'or letter[i]=='i'or letter[i]=='o'or letter[i]=='u'):
      ans += 1
  print(ans)
vowels(letter)

"""9.Automated event remainder"""

import datetime
currentdatetime=datetime.datetime.now()
print(currentdatetime)

"""10.Robust financial calculator"""

def add(num1,num2):
  try:
    num1=int(input("enter first number"))
    num2=int(input("enter second number"))
    total=num1 + num2
    print(total)
  except:
    print("enter correct datatype")
  add(num1,num2)

"""11.Online polling system"""

try:
  a=int(input("enter data in online polling system"))
  print("Correct data")
except ValueError:
  print("print integer only")

"""12.Scientific data processing tool"""

def division(a,b):
 try:
  a=int(input("enter first number"))
  b=int(input("enter second number"))
  ans=a/b
  print("The answer is:" + str(ans))
 except ZeroDivisionError:
  print("Division by zero not possible")

"""13.Automated reporting system"""

def logfile(filename):
  try:
   daily_report=open('content/logfile/daily_report_status.csv','w')
   daily_report.write('update logfile')
   print("Update the daily report status in logfile")
  except FileNotFoundError:
   print("file doesn't exist")

"""14.Corporate compliance review tool"""

logfile=open('content/logfile/daily_report_status.csv','r')
logfile.read()
logfile.close()

"""15.Dynamic content creation engine"""

logfile=open('','r')