# -*- coding: utf-8 -*-
"""Linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JH5rXVOkg2BgngMcFGYnkmejh-LEG_Vi
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('/content/expenses.csv')

df.head()

df.info()

df.describe()

df.isnull().sum()

df['bmi']=df['bmi'].fillna(df['bmi'].mean())

df.isnull().sum()

df.duplicated().sum()

"""Outlier Detection"""

import seaborn as sns
age_outliers=sns.boxplot(df['age'])

bmi_outliers=sns.boxplot(df['bmi'])
print(df[df['bmi']>45].count())

charges_outliers=sns.boxplot(df['charges'])
print(df[df['charges']>40000].count())

"""Removing Outliers"""

def remove_outliers(A,threshold):
 return df[A<threshold]
df=remove_outliers(df['bmi'],45)
df=remove_outliers(df['charges'],40000)

df.count()

"""Encoding"""

#encoding categorical features
from sklearn.preprocessing import LabelEncoder
label_encode=LabelEncoder()
df['sex']=label_encode.fit_transform(df['sex'])
df['smoker']=label_encode.fit_transform(df['smoker'])
df['region']=label_encode.fit_transform(df['region'])

df.head()

df.info()

"""Data Cleaning and Feature Selection"""

duplicates=df.duplicated(keep=False)
df['duplicate']=duplicates
df[df['duplicate']==True].count()

df = df[df['duplicate'] == False]
df = df.drop('duplicate',axis=1)

df.duplicated().sum()

"""Train test split"""

X=df.drop('charges',axis=1)
y=df['charges']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

"""Build Model"""

regressor = LinearRegression()
trained_model = regressor.fit(X_train,y_train)
y_pred = trained_model.predict(X_test)

"""Evaluation Metric"""

from sklearn.metrics import r2_score,mean_squared_error
import numpy as np

mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

print('MSE: ',mse)
print('RMSE: ',rmse)
print('R-Squared: ',r2)

